"""empty message

Revision ID: 2a127d3c58a0
Revises: 809a4d88e2be
Create Date: 2024-10-04 20:22:33.554809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a127d3c58a0'
down_revision = '809a4d88e2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_user_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_user_name_key', ['user_name'])

    # ### end Alembic commands ###
