"""empty message

Revision ID: 5865238f1f77
Revises: 2a127d3c58a0
Create Date: 2024-10-04 20:36:02.777818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5865238f1f77'
down_revision = '2a127d3c58a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_name', sa.String(length=50), nullable=False),
    sa.Column('poblacion', sa.String(length=50), nullable=False),
    sa.Column('clima', sa.String(length=50), nullable=False),
    sa.Column('diametro', sa.Integer(), nullable=False),
    sa.Column('periodo_rotacion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planet_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    # ### end Alembic commands ###
