"""empty message

Revision ID: 809a4d88e2be
Revises: a5cffa318ac2
Create Date: 2024-10-04 20:09:26.636763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809a4d88e2be'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('user_lastname', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.create_unique_constraint(None, ['user_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('date')
        batch_op.drop_column('user_lastname')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
