"""empty message

Revision ID: f9a20443d9a5
Revises: fe50bab0794a
Create Date: 2024-10-04 22:03:40.443634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a20443d9a5'
down_revision = 'fe50bab0794a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personaje', sa.String(length=50), nullable=False),
    sa.Column('planeta_origen', sa.String(length=50), nullable=False),
    sa.Column('altura', sa.String(length=50), nullable=False),
    sa.Column('peso', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('altura'),
    sa.UniqueConstraint('personaje'),
    sa.UniqueConstraint('peso'),
    sa.UniqueConstraint('planeta_origen')
    )
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personaje_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'characters', ['personaje_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('personaje_id')

    op.drop_table('characters')
    # ### end Alembic commands ###
