"""empty message

Revision ID: fc5e48dd0640
Revises: f9a20443d9a5
Create Date: 2024-10-07 21:53:13.770220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5e48dd0640'
down_revision = 'f9a20443d9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('characters_personaje_key', type_='unique')
        batch_op.create_unique_constraint(None, ['character'])
        batch_op.drop_column('personaje')

    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favoritos_personaje_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'characters', ['character_id'], ['id'])
        batch_op.drop_column('personaje_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favoritos_personaje_id_fkey', 'characters', ['personaje_id'], ['id'])
        batch_op.drop_column('character_id')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personaje', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('characters_personaje_key', ['personaje'])
        batch_op.drop_column('character')

    # ### end Alembic commands ###
